version: '2'
services:
    bookingapp-app:
        image: bookingapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bookingapp-mysql:3306/bookingapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    bookingapp-mysql:
        extends:
            file: mysql.yml
            service: bookingapp-mysql
